camel:
  springboot:
    main-run-controller: true
    allow-use-original-message: true

fleetlize.broker-url: tcp://localhost:61616

spring:
  sleuth:
    sampler:
      probability: 1.0
  main:
    lazy:
      initialization: true
